version: '3.8'

services:
  server:
    image: darryljoo/hd-prep-server-prod
    container_name: hd-prep-server-prod
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - /usr/src/app/node_modules
    restart: unless-stopped
    command: npm start
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - server
    restart: unless-stopped
