services:
  server:
    build: ./
    env_file:
      - .env
    container_name: hd-prep-server-prod
    expose: [ "3000" ]
    init: true
    stop_signal: SIGTERM
    stop_grace_period: 30s
    restart: unless-stopped
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    init: true
    stop_grace_period: 10s
    depends_on:
      - server
    volumes:
      - certs:/etc/letsencrypt
      - certbot_conf:/var/lib/letsencrypt
    restart: unless-stopped
  certbot:
    image: certbot/certbot:latest
    volumes:
      - certs:/etc/letsencrypt
      - certbot_conf:/var/lib/letsencrypt
    entrypoint: >
      sh -c "
        certbot certonly --non-interactive --agree-tos
        --standalone -m joo.darryl@gmail.com
        -d api.hdprep.me
        --keep-until-expiring &&
        crond -f
      "
volumes:
  certs:
  certbot_conf:
