services:
  server-dev:
    image: darryljoo/hd-prep-server-dev
    container_name: hd-prep-server-dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - /usr/src/app/node_modules
    command: npm run dev
